# -*- coding:utf-8 -*-

from . import contratos_compra_venta
from . import tipo_contrato
from . import pais
from . import estado
from . import ciudad
from . import localidad
from . import huertas
from . import certificaciones
from . import organismos_verificadores
from . import registros_certificaciones
from . import facturas_cfdi_3_3
from . import connection_sql_server
from . import connection_sql_server_corte
from . import huertas_contratos_terceros
from . import extension_cuentas_bancarias
from . import extension_partner_sat
from . import opinion_cumplimiento_sat
from . import ine_sat
from . import interfaz_lotes
from . import sat_documentos_lotes
from . import cp_cuadrillas
from . import cp_tipo_cuadrilla
from . import cif
from . import lotes_cfdis_rel
from . import lotes_account_move_line
from . import recepciones_lotes
from . import account_payment_extends
from . import account_invoice_sat_catalogue
from . import product_product_extends
from . import pagos_layout
from . import purchase_order_extends
from . import cfdi_reps
from . import cfdi_reps_detail
from . import pagos_doctos_rel
from . import presupuesto_lotes
from . import presupuesto_flete
from . import reporte_saldos
from . import lotes_view
from . import account_register_payment_extends
from . import autorizaciones_cancelaciones
from . import modify_original_size_binaries